### ISSUE TITLE
Some packages are missing

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hxdoc#2]
```
./go2hxdoc -seq -dir stdgo
```
```
Creating: stdgo/crypto/elliptic/internal/nistec/README.md
Creating: stdgo/crypto/hmac/README.md
Creating: stdgo/crypto/internal/randutil/README.md
Creating: stdgo/crypto/internal/subtle/README.md
Creating: stdgo/crypto/md5/README.md
Creating: stdgo/crypto/rand/README.md
Creating: stdgo/crypto/rc4/README.md
Creating: stdgo/crypto/rsa/README.md
Creating: stdgo/crypto/sha1/README.md
Creating: stdgo/crypto/sha256/README.md
Creating: stdgo/crypto/sha512/README.md
Creating: stdgo/crypto/tls/README.md
Creating: stdgo/crypto/x509/README.md
Creating: stdgo/crypto/x509/pkix/README.md
Creating: stdgo/database/sql/README.md
Creating: stdgo/debug/dwarf/README.md
Creating: stdgo/debug/elf/README.md
Creating: stdgo/debug/gosym/README.md
Creating: stdgo/debug/macho/README.md
Creating: stdgo/debug/pe/README.md
Creating: stdgo/debug/plan9obj/README.md
Creating: stdgo/embed/README.md
Creating: stdgo/encoding/README.md
Creating: stdgo/encoding/ascii85/README.md
Creating: stdgo/encoding/asn1/README.md
Creating: stdgo/encoding/base32/README.md
Creating: stdgo/encoding/base64/README.md
Creating: stdgo/encoding/binary/README.md
Creating: stdgo/encoding/csv/README.md
Creating: stdgo/encoding/gob/README.md
Creating: stdgo/encoding/hex/README.md
Creating: stdgo/encoding/pem/README.md
Creating: stdgo/expvar/README.md
Creating: stdgo/flag/README.md
Creating: stdgo/hash/README.md
Creating: stdgo/hash/adler32/README.md
Creating: stdgo/hash/crc32/README.md
Creating: stdgo/hash/crc64/README.md
Creating: stdgo/hash/fnv/README.md
Creating: stdgo/hash/maphash/README.md
Creating: stdgo/html/README.md
Creating: stdgo/html/template/README.md
Creating: stdgo/image/README.md
Creating: stdgo/image/color/README.md
Creating: stdgo/image/color/palette/README.md
Creating: stdgo/image/draw/README.md
Creating: stdgo/image/gif/README.md
Creating: stdgo/image/internal/imageutil/README.md
Creating: stdgo/image/jpeg/README.md
Creating: stdgo/image/png/README.md
Creating: stdgo/index/suffixarray/README.md
Creating: stdgo/internal/README.md
Creating: stdgo/internal/execabs/README.md
Creating: stdgo/internal/obscuretestdata/README.md
Creating: stdgo/internal/profile/README.md
Creating: stdgo/internal/sysinfo/README.md
Creating: stdgo/internal/xcoff/README.md
Creating: stdgo/io/README.md
Creating: stdgo/io/fs/README.md
Creating: stdgo/io/ioutil/README.md
Creating: stdgo/log/README.md
Creating: stdgo/log/syslog/README.md
Creating: stdgo/math/README.md
Creating: stdgo/math/big/README.md
Creating: stdgo/math/cmplx/README.md
Creating: stdgo/math/rand/README.md
Creating: stdgo/mime/README.md
Creating: stdgo/mime/multipart/README.md
Creating: stdgo/mime/quotedprintable/README.md
Creating: stdgo/net/README.md
Creating: stdgo/net/http/cgi/README.md
Creating: stdgo/net/http/cookiejar/README.md
Creating: stdgo/net/http/fcgi/README.md
Creating: stdgo/net/http/httptrace/README.md
Creating: stdgo/net/http/httputil/README.md
Creating: stdgo/net/http/internal/README.md
Creating: stdgo/net/http/pprof/README.md
Creating: stdgo/net/mail/README.md
Creating: stdgo/net/rpc/README.md
Creating: stdgo/net/rpc/jsonrpc/README.md
Creating: stdgo/net/smtp/README.md
Creating: stdgo/net/textproto/README.md
Creating: stdgo/net/url/README.md
Creating: stdgo/os/README.md
Creating: stdgo/os/signal/README.md
Creating: stdgo/os/user/README.md
Creating: stdgo/path/README.md
Creating: stdgo/path/filepath/README.md
Creating: stdgo/plugin/README.md
Creating: stdgo/regexp/README.md
Creating: stdgo/regexp/syntax/README.md
Creating: stdgo/runtime/README.md
Creating: stdgo/runtime/cgo/README.md
Creating: stdgo/runtime/metrics/README.md
Creating: stdgo/runtime/trace/README.md
Creating: stdgo/strconv/README.md
Creating: stdgo/syscall/README.md
Creating: stdgo/syscall/js/README.md
```

I don't see unicode or math/bits, it seems only the packages that fail are generated.

Also if you have a recommendation of what command to run inside of go2hx for the action that would be helpful.

**Comment by elliott5** [comment]
You are entirely correct, I am mystified why ... but will investigate!

While we are developing, I would expect the low resource batch command `-seq` to also include `-force` (so as not to skip if a README.md already exists). So:
```
./go2hxdoc -seq -force -dir stdgo
```

**Comment by elliott5** [comment]
For `stdgo` only,  because of the way that haxe works (it looks for class names in the library first) `go2hxdoc` can only document the code that is actually inside the library.

@PXshadow please look at the .sh files that I will push shortly:
- doc_only_batch_stdgo.sh (for what you are trying to do above)
- doc_and_test_stdgo.sh (for full parallel testing)

**Comment by PXshadow** [comment]
Resolved now on my ends thanks!

**Comment by PXshadow** [comment]
I tested it locally and it was working but for some reason not on the github action runner if you could take a look that would be quite helpful @elliott5 https://github.com/go2hx/go2hx/actions/runs/3076255874/jobs/4970287221

**Comment by elliott5** [comment]
The directory in `-dir /a/b/c/stdgo` must have exactly the same path as `haxelb  libpath go2hx`+`stdgo`.

I can look further after eating dinner.

**Comment by PXshadow** [comment]
Wonderful thank you @elliott5 

When go2hx's action runs again it will now show the dir being used.https://github.com/go2hx/go2hx/commit/ea07ae9bb1c2e0c956c7dc6be61256f419377daa

Here is all of the commands I am using for the doc part of the workflow:
```sh
go get github.com/go2hx/go2hxdoc
go build github.com/go2hx/go2hxdoc
./go2hxdoc -dir `npx haxelib libpath go2hx`stdgo -stats -force -seq
```

This line is being used both by the stdgo gen and doc gen:
```sh
npx haxelib dev go2hx .
```

**Comment by elliott5** [comment]
Certainly debug info would be helpful, as the code is not obviously wrong.

I think you are right that the commit id in the path may be a possible issue.

The other that occurs to me is having a case-sensitive file system (rather then OSX which is case-in-sensitive) because I presume it is running on Linux.

I look forward to seeing the results.

**Comment by elliott5** [comment]
I'm no wiser after seeing the latest run.

I'll try and get it working on Ubuntu tomorrow, to see if there are any issues in that direction.

**Comment by elliott5** [comment]
Just set-up Ubuntu for the test.
Noticed I did:
```
$ lix install haxe nightly
$ lix use haxe nightly
```
Which is not in the GitHub Action

**Comment by elliott5** [comment]
I can't even get `go2hx` to work on Ubuntu at the moment, and I'm conscious I'm running out of time (The Queen's funeral & going on holiday).

I'm stuck at trying to compile "Hello World":
```
elliott@virtualubuntu:~/go2hx$ npx haxelib run go2hx hw.go --interp
Cloning into 'tools'...
/home/elliott/haxe/haxelib/go2hx/git/haxe_libraries/hxnodejs.hxml:1: classpath /home/elliott/haxe/haxelib/hxnodejs/12.1.0/github/e37e79fce8a2a2177a0a73ce9d8eff2acdbcfa8b/src is not a directory or cannot be read from
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/elliott/haxe/haxelib/go2hx/git/build.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
elliott@virtualubuntu:~/go2hx$ npx haxelib list
go2hx: [git]
hxnodejs: [12.1.0]
```

...suggestions welcome @PXshadow !

**Comment by elliott5** [comment]
It also occurs to me that commands inside the Github Actions are prefaced by `npx ` to make them work.

When `go2hxdoc` runs commands it does not prefix them with ``npx `,

**Comment by PXshadow** [comment]
> Just set-up Ubuntu for the test. Noticed I did:
> 
> ```
> $ lix install haxe nightly
> $ lix use haxe nightly
> ```
> 
> Which is not in the GitHub Action

It's done on the ``lix download`` step

**Comment by PXshadow** [comment]
> It also occurs to me that commands inside the Github Actions are prefaced by `npx ` to make them work.
> 
> When `go2hxdoc` runs commands it does not prefix them with ``npx `,

That's probably it then, I should've realized that sorry, I have had that issue before with the test runner I even have a flag for it, to use npx version. I'll make an issue for it, I believe that just do it. Nice find @elliott5

**Comment by PXshadow** [comment]
https://github.com/go2hx/go2hxdoc/issues/4 this issue cleared should cause this issue to clear as well.
