### ISSUE TITLE
Create Index markdown file

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hxdoc#3]
Have a flag to enable an index markdown (setting the filepath with the flag would be preferred) So the index markdown can link to all of the generated markdown files.

**Comment by elliott5** [comment]
I think the index is missing because of  issue #2, it should be generated automatically.

Putting the index in a different location than the top level directory (`stdgo`/`golibs`) would be more work because of the relative links between all the .md files.

**Comment by PXshadow** [comment]
> Putting the index in a different location than the top level directory (`stdgo`/`golibs`) would be more work because of the relative links between all the .md files.

No worries then, and I see!

**Comment by PXshadow** [comment]
Working great!
