### ISSUE TITLE
Inline code block gets unescaped

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hxdoc#5]
The header functions using `` are getting escaped with \\`

The idea is to have a function header that looks like this at source:
```md
## function `isUpper`
```

not this:

```md
## function \`isUpper\`
```

**Comment by elliott5** [comment]
I can't find a way to have an internal href (to enable the link from the index) to a header containing special characters.

But I have made the index entries into `code` items where they are a function signature.

**Comment by PXshadow** [comment]
This is resolved, thank you for looking into this @elliott5 :) , closed due to technical limitation of markdown linking from index to href with special characters (as noted above).
