### ISSUE TITLE
U+FFFD � REPLACEMENT CHARACTER in internal/cpu doc

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hxdoc#8]
Under the [variables of internal/cpu header](https://github.com/go2hx/go2hx/tree/master/stdgo/internal/cpu#variables) Lots of unknown chars are found for example arm64 var doc:

The booleans in ARM contain the correspondingly named cpu feature bit.��// The struct is padded to avoid false sharing.

**Comment by elliott5** [comment]
My best guess from looking at the Go code is that the unknown characters are: CR LF
I'll fix it.
